.TH LIBVDEPLUG_P2P 1 "August 23, 2016" "Virtual Distributed Ethernet"
.SH NAME
libvdeplug_ptp - vdeplug module for point to point connections
.SH SYNOPSIS
libvdeplug_ptp.so
.SH DESCRIPTION
This module interconnects two vde supporting tools by a point to point
communication line.
This module of libvdeplug4 can be used in any program supporting vde like
\fBvde_plug\fR, \fBkvm\fR, \fBqemu\fR, \fBuser-mode-linux\fR and \fBvirtualbox\fR.

The vde_plug_url syntax of this module is the following:
.RS
.br
\fBptp://\fIpath_of_the_socket\fR
.RE

.SH EXAMPLES
.B ptp:///tmp/sock
.br
The same vde_plug_url can be used at both ends of the connection.
The first program creates the socket \fB/tmp/sock\fR. The second program connects to
\fB/tmp/sock\fR, when it discovers that the socket already exists.
.SH NOTICE
Virtual Distributed Ethernet is not related in any way with
www.vde.com ("Verband der Elektrotechnik, Elektronik und Informationstechnik"
i.e. the German "Association for Electrical, Electronic & Information
Technologies").
.SH SEE ALSO
\fBvde_plug\fP(1),
