.TH LIBVDEPLUG_MACVTAP 1 "August 18, 2023" "Virtual Distributed Ethernet"
.SH NAME
libvdeplug_macvtap - vdeplug module: macvtap interface 
.SH SYNOPSIS
libvdeplug_macvtap.so
.SH DESCRIPTION
This is the standard vdeplug module to connect a MACVTAP interface.
This module of libvdeplug4 can be used in any program supporting vde like
\fBvde_plug\fR, \fBkvm\fR, \fBqemu\fR, \fBuser-mode-linux\fR and \fBvirtualbox\fR.
\fBtunctl\fR or \fBvde_tunctl\fR can be used to  preconfigure a TAP device for use by a particular user.

The vde_plug_url syntax of this module is the following:
.RS
.br
\fBmacvtap://\fImacvtap_interface_name\fR
.RE

.SH EXAMPLES
.B macvtap://macvlan0
.br
This vde_plug_url refers the macvtap interface named \fBmacvlan0\fR, for instance created by
the command:
.br
.B ip link add link eth0 name macvlan0 type macvtap mode bridge

.SH NOTICE
Virtual Distributed Ethernet is not related in any way with
www.vde.com ("Verband der Elektrotechnik, Elektronik und Informationstechnik"
i.e. the German "Association for Electrical, Electronic & Information
Technologies").
.SH SEE ALSO
\fBvde_plug\fP(1),
